namespace CSharpFundamentals.Exercises;

public static class Ch09_RandomNumbers
{
    public static void Run()
    {
        // Chapter 9: RandomNumbers
        // this is not true random numbers, rather Pseudorandom numbers
        // Pseudorandom numbers are generated by an algorithm (deterministic) from a seed; they look random, but are reproducible.
        // True random numbers come from physical sources of entropy (noise, hardware RNG) and are not algorithmically predictable.

        Random random = new Random(); // instantiates new random project

        int num1 = random.Next(1, 7); // Next(min, max): min is inclusive, max is exclusive -> Next(1, 7) gives 1..6
        int num2 = random.Next(1, 7); // last number is exclusive
        int num3 = random.Next(1, 7);

        // double num = random.NextDouble(); // random for double typed variables

        Console.WriteLine(num1);
        Console.WriteLine(num2);
        Console.WriteLine(num3);

        Console.ReadKey();
    }
}
